### PR TITLE
fix: #907 move wxt devDeps execa to dependencies

### LINKED ISSUE #907: `wxt submit` not printing anything to console
### Describe the bug

image

From https://discord.com/channels/1212416027611365476/1270367714900185200/1270367714900185200

### Reproduction

https://github.com/AlexGodard/wxt-turborepo-no-output-repo

### Steps to reproduce

```sh
cd wxt-inside-turborepo/apps/wxt-0.19.4
pnpm install
pnpm wxt submit
```

### System Info

```shell
Did not report on discord
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by 1natsu172**
fix #907 

I was looking about #907 and found that the error was caused by dynamic import `execa`.

In non-monorepo, I think it was by chance that `execa@8` was found and working so far (What a surprise, up until now, execa was running on `@8`!). But in monorepo, there are cases where `execa@5` is found before `execa@8`, due to pnpm hoist and module resolution.

> Until 0.19.4: not found the expect `execa@9.3.0`
image

Here is a screenshots of the patch in `node_modules/wxt` and logging of `import.meta.resolve` etc.

| Monorepo#wxt@0.19.4 | Standalone#wxt@0.19.4 |
|--------|--------|
|  found `execa@5.1.1` | found `execa@8.0.1`  |
| image | image |

### CODE REVIEW

**Review by aklinker1 — APPROVED** [review]

**Comment by 1natsu172** [comment]
@aklinker1 Umm, CI has been failed. 

Looked at the lock file and found that the internal peer-dependent rollup was v3=>v4, so `@ts-expect-error` was no longer needed. I have added a commit that removes it.

**Comment by aklinker1** [comment]
Yeah, this is something that annoys me. The vite and roll-up versions get out of sync somehow, and I just end up removing or adding ts-expect-error comments lol.

If you know how to solve this, feel free to open a PR

**Comment by 1natsu172** [comment]
@aklinker1 Ah, it's a lockfile issue. More like a pnpm full-resolution issue. Normal `pnpm i` does not update past peers once locked.

The solution is to clean up lockfile sometimes. Use either `pnpm i --resolution-only` or `pnpm i --fix-lockfile` can be  update the peers.

---

FYI: The pnpm source codes 😄 
https://github.com/pnpm/pnpm/blob/d367c93e37bb352d9c67e7b56675115cd3d55a2a/pkg-manager/core/src/install/index.ts#L363-L366
https://github.com/pnpm/pnpm/blob/d367c93e37bb352d9c67e7b56675115cd3d55a2a/pkg-manager/plugin-commands-installation/src/install.ts#L336-L339

**Comment by aklinker1** [comment]
Interesting, didn't know about either of those flags, good to know! I would rather just run that command manually if something break rather than add a post-install step. Also, I found for `--resolution-only` to work, I had to run a regular install afterwords. I only had to run `pnpm i --fix-lockfile` for it to work. So good to know I guess.

**Review by aklinker1 — APPROVED** [review]

**Comment by 1natsu172** [comment]
Yes, need to apply an update to the lock file. If manual execution doesn't bother you, that's fine!

**Pull request merged**
