### PR TITLE
docs: Added DocVersionRedirector to "Using WXT" section

### PR DESCRIPTION
**Pull request by leos**
Adding [DocVersionRedirector](https://github.com/leos/DocVersionRedirector/). If you have a few moments, would love a quick look at the code and any feedback on how I'm using WXT.

### CODE REVIEW

**Comment by aklinker1** [comment]
Cool project! I checked it out, everything looks good except for the background entrypoint, the `browser.runtime.onInstalled` should go inside the main function of `defineBackground`. 

https://github.com/leos/DocVersionRedirector/blob/147481ab1b206cae3c36aad06dd04ec96e19b3fb/src/entrypoints/background.ts#L3-L6

I would actually expect your build to crash, including a side-effect like that in an entrypoint - if you keep adding code outside the main function, you'll eventually run into #336. For example, notice how all the code is inside the main function in these background scripts:

- https://github.com/aklinker1/github-better-line-counts/blob/2454214c2026628639f2d7ac9063ba42f4b8a18e/src/entrypoints/background.ts
- https://github.com/wxt-dev/wxt/blob/50e8c86ce993347425b953bfd472f36e1f15e90b/demo/src/entrypoints/background.ts
- https://github.com/anime-skip/player/blob/f07125a19341fac635967a793d16d1611e7bc44a/apps/extension/src/entrypoints/background.ts

Otherwise it's looking good! I don't use react much, hows the developer experience developing a react-based extension with WXT? HMR working correctly?

**Comment by aklinker1** [comment]
> Connected to this discussion, is there a discord/slack/gitter for wxt? It may make it a bit easier to communicate about the extension (although, you may not want to do it in chat :-) ).

I've hesitated creating a discord because I don't like being overrun with notifications lol. But I need to do it now that WXT has almost hit 2k stars.

> Do I need to also do the same for unlisted scripts?

Neither of those files are unlisted scripts. Unlisted scripts are JS/TS files in the entrypoints directory that aren't content scripts or background scripts.

https://wxt.dev/entrypoints/unlisted-scripts.html

Unlisted scripts are scripts you inject dynamically, usually by adding a `script` block to the page from a content script. Those scripts run in the page's context, and have access to more information about the website. In your case, helper files or utils aren't considered unlisted scripts. So you don't need `defineUnlistedScript` for those.

**Comment by leos** [comment]
> I've hesitated creating a discord because I don't like being overrun with notifications lol. But I need to do it now that WXT has almost hit 2k stars.

No worries - do what works best for you!

> Neither of those files are unlisted scripts. Unlisted scripts are JS/TS files in the entrypoints directory that aren't content scripts or background scripts.

I see. I think I had to add that because those files weren't being packaged into the build w/o `defineUnlistedScript`. Let me try removing it and see what happens.

**Comment by leos** [comment]
Everything works great without `defineUnlistedScript`, thanks again!

**Comment by aklinker1** [comment]
As long as you import them, they'll be bundled into the final output. They may not showup as separate files or have the same file name, but if you're importing them, they'll be there.

**Pull request merged**
