### PR TITLE
chore: Upgrade React to v19 in demo

### LINKED ISSUE #1268: Update React Template to v19
### Feature Request

Update the react template so it uses react version 19. 

This should be as easy as upgrading the UV to plug-in and the dependencies:

https://github.com/wxt-dev/wxt/blob/main/templates%2Freact%2Fpackage.json

> Also, should those be peer dependencies?

#### Is your feature request related to a bug?

https://discord.com/channels/1212416027611365476/1224505556346212515/1316317864755724288

### What are the alternatives?

N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by nishu-murmu**
This closes #1268

### CODE REVIEW

**Review by aklinker1 — APPROVED** [review]
Thanks, looks good! We can ignore the failed check, just because this PR is a fork.

**Comment by aklinker1** [comment]
Do we also need to upgrade `@wxt-dev/module-react`?

**Comment by nishu-murmu** [comment]
> Do we also need to upgrade `@wxt-dev/module-react`?

I thought as we or rather you are developing, we might need latest version for testing purposes, as I've often used wxt-demo for fixing bugs and all,
Also just to be in sync with the latest version. If you feel otherwise then I'll revert it back.

**Comment by aklinker1** [comment]
I haven't looked into what's required for react 19, but if we're updating the template, then that's what people are going to use and we need to update the module as well.

**Comment by nishu-murmu** [comment]
So this is correct right? But why ignore the test checks, was it breaking in the main?

**Review by aklinker1 — CHANGES_REQUESTED** [review]

**Review by aklinker1 — APPROVED** [review]

**Pull request merged**
