### PR TITLE
docs: Add MS Edge TTS to homepage

### PR DESCRIPTION
**Pull request by yacine-bens**

### CODE REVIEW

**Review by aklinker1 — APPROVED** [review]
Cool extension, I've been doing some TTS stuff myself, what service are you using?

**Comment by yacine-bens** [comment]
I'm glad you like it. 
It's on the title LOL. I'm using [MsEdgeTTS](https://github.com/Migushthe2nd/MsEdgeTTS). It is based on Azure Speech Service module that uses the Microsoft Edge Read Aloud API.

**Comment by aklinker1** [comment]
Ah lol, I wasn't sure if you were just targetting edge users or something 😂 but that makes sense. I've mainly ever use GCP's TTS service, but have heard good things about Azure and AWS's... I should give them a go.

**Comment by yacine-bens** [comment]
I tried different TTS services but I can't say I found better than
Elevenlabs. They also provide Speech-to-Speech and it's amazing. They offer
10k characters per month for free.
It's my next extension project 😁

**Pull request merged**
