### PR TITLE
docs: Added "RespondEasy" to homepage

### PR DESCRIPTION
**Pull request by rgrebski**
Added Respond Easy plugin that allows to generate review responses with AI. Built by me

### CODE REVIEW

**Review by aklinker1 — APPROVED** [review]
Thanks!

**Comment by aklinker1** [comment]
Haha looks like my API to load extension details is down... I'll get that fixed soon lol

**Comment by rgrebski** [comment]
> Haha looks like my API to load extension details is down... I'll get that fixed soon lol

Yeah, I saw something is wrong with list of plugins on wxt.dev :⁠-⁠)

Sorry for putting plugin at the top (it was worth trying 😉) and thx for reordering.

**Comment by aklinker1** [comment]
> Sorry for putting plugin at the top (it was worth trying 😉) and thx for reordering.

Haha the order doesn't really matter, the extensions are sorted by a combination of user count and rating.

**Comment by aklinker1** [comment]
OK, that problem has been fixed! https://github.com/wxt-dev/queue/issues/2

**Pull request merged**
