### PR TITLE
docs: Add "EyeDropper" to homepage

### PR DESCRIPTION
**Pull request by kepi**
EyeDropper is using WXT too.

### CODE REVIEW

**Comment by kepi** [comment]
I'm not sure what I'm doing wrong, but I don't see Eye Dropper on deploy preview. I tried both simple extension id and with slug.

Extension page is:

https://chromewebstore.google.com/detail/eye-dropper/hmdcmlfkchdmnmnmheododdhjedfccka

It shouldn't be hard to miss, as it should be in first place.

**Comment by aklinker1** [comment]
Looks like my API was couldn't crawl your extension user count! I'll get this fixed, not anything on your side.

```
$ curl 'https://queue.wxt.dev/api' -X POST -H 'content-type: application/json' --data-raw '{"query":"{ chromeExtension(id: \"hmdcmlfkchdmnmnmheododdhjedfccka\") { weeklyActiveUsers  } }"}'
{
  "errors": [
    {
      "message": "Int cannot represent non-integer value: NaN",
      "locations": [
        {
          "line": 18,
          "column": 5
        }
      ],
      "path": [
        "chromeExtension",
        "weeklyActiveUsers"
      ]
    }
  ],
  "data": {
    "chromeExtension": null
  }
}
```

**Comment by aklinker1** [comment]
There we go, it's showing up now. 

> Fix for reference: https://github.com/wxt-dev/queue/compare/v0.3.15...v0.3.17#diff-1e146a2211027de67998c9680ef5bdf773000c393e95214228d50c0aeee33ae9

**Review by aklinker1 — APPROVED** [review]
Thanks for trying out and using WXT!

**Comment by kepi** [comment]
Thanks for WXT! I'm still discovering all posibilities, but it helps a lot.

**Pull request merged**
