### PR TITLE
docs: Update CRXJS Firefox Compatibility

### PR DESCRIPTION
**Pull request by Malix-off**

### CODE REVIEW

**Review by aklinker1 — APPROVED** [review]

**Review by aklinker1 — COMMENTED** [review]
Looks like this has only been released in the v2 beta, 5 months ago. I don't think it's safe to say it supports firefox yet. I'll update it to a green checkmark with the comment about the beta version.

**Comment by aklinker1** [comment]
Ugh, the merge conflicts are really bad :( I'll fix them and get this merged later today

**Comment by Malix-off** [comment]
Hey aaron!

> Looks like this has only been released in the v2 beta, 5 months ago.

Absolutely,
In fact, I was doing a fork-repo deletion tour, and I saw I didn't opened the PR for this one, so I'm sorry for the conflicts there are now
I think the real problem is that docs/guide/compare.md seems to have been relocated, but I don't know where precisely nor at what LOC

**Comment by aklinker1** [comment]
> In fact, I was doing a fork-repo deletion tour, and I saw I didn't opened the PR for this one, so I'm sorry for the conflicts there are now

No worries! All done now, merging :)

**Pull request merged**
