### PR TITLE
feat(hooks): Move `entrypoints:resolved` before debug logs and add `entrypoints:found`

### PR DESCRIPTION
**Pull request by abhigyantrips**
as mentioned in #1072, there's a requirement for a hook to manipulate entrypoint resolution before loading them.

1. as there have been changes to the `findEntrypoints()` function since the issue, it's a bit outdated and the solution right now is to just move the `entrypoints:resolved` hook to before logging.
2. as per a convo with @aklinker1 we should also introduce an `entrypoints:paths` hook to be able to manipulate the `entrypointInfo` variable.

### CODE REVIEW

**Comment by abhigyantrips** [comment]
probably should change `entrypointInfos` to just `infos`.

**Review by aklinker1 — COMMENTED** [review]
Nice, this is perfect!

Thoughts on renaming `entrypoints:paths` to `entrypoints:found` or `entrypoints:discovered`? This would better align with the `noun:past-tense-verb` naming convention we use for most of the other hooks. I realized `entrypoints:paths` wasn't a very good name after sleeping on it lol.

**Comment by abhigyantrips** [comment]
`entrypoints:found` seems to stick well with `entrypoints:grouped` and `entrypoints:resolved`. will make those changes now.

any changes required to the addition in the docs?

**Comment by aklinker1** [comment]
> any changes required to the addition in the docs?

Maybe a recipe on the modules page for adding an entrypoint using the new hook.

**Review by aklinker1 — APPROVED** [review]

**Comment by aklinker1** [comment]
Alright, thanks for adding this. Great quality PR too 👍

**Comment by aklinker1** [comment]
Hmm, not sure why those checks are failing... I'll get it sorted out and get the PR merged soon. Holidays and family in town starting tomorrow, so it might be a few days before I can look into this.

**Comment by aklinker1** [comment]
Looks like it's related to vite 6.0.4: https://github.com/wxt-dev/wxt/issues/1293

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.23

**Pull request merged**
